# Assignment 1

<b>Q 1. Perform PCA for the following dataset. This dataset shows 10 measurements performed for measuring
length, width and thickness of a Si wafer.


In [51]:
import numpy as np

In [52]:
## the dataset is of length , width and thickness we have to analyse the priciple component length in this system
X = np.array([[7,4,3],
[4,1,8],
[6,3,5],
[8,6,1],
[8,5,7],
[7,2,9],
[5,3,3],
[9 ,5, 8],
[7 ,4 ,5],
[8 ,2, 2]])


In [53]:
# here in this data of m = no. of measurement types and n = no. of data trials
##Transpose of matrix is needed to calculate the covariance matrix of 3 by 3 and satisfying the above m*n type.
c = X- np.mean(X,axis = 0)
[m,n] = X.shape
covariance = np.matmul(c.T,c)/(m-1)
print(covariance)


[[ 2.32222222  1.61111111 -0.43333333]
 [ 1.61111111  2.5        -1.27777778]
 [-0.43333333 -1.27777778  7.87777778]]


In [54]:
U,D,V = np.linalg.svd(covariance)
## 2nd and 3rd components are the most important factor 

In [55]:
U
## Eigen vectors of the 3 by 3 covariance matrix

array([[-0.1375708 ,  0.69903712, -0.70172743],
       [-0.25045969,  0.66088917,  0.70745703],
       [ 0.95830278,  0.27307986,  0.08416157]])

In [56]:
D
## eigen values of the covariance matrix represent the weights of the particular component.

array([8.27394258, 3.67612927, 0.74992815])

In [57]:
sum = D[0]+D[1]+D[2]
ratio = []
for i in D:
    ratio.append(i/sum)
print("Expained variance ratio of significance:",np.sort(ratio)[::-1])
## length corresponds to 65.2% of the data and width correspond to 29% of the data where thickness is not significant.

Expained variance ratio of significance: [0.65149154 0.289459   0.05904946]


In [58]:
# Final transformation matrix is similar to the transformation derived from the 
final = np.matmul(U.T,c.T)
print(final.T)

[[-2.15142276 -0.17311941  0.10681648]
 [ 3.80418259 -2.88749898  0.5104355 ]
 [ 0.15321328 -0.98688598  0.26941001]
 [-4.7065185   1.30153634  0.65167999]
 [ 1.29375788  2.27912632  0.44919235]
 [ 4.0993133   0.1435814  -0.80312818]
 [-1.62582148 -2.23208282  0.80281431]
 [ 2.11448986  3.2512433  -0.16837351]
 [-0.2348172   0.37304031  0.27513962]
 [-2.74637697 -1.06894049 -2.09398657]]


In [59]:
# from sklearn library we impored PCA and compared with the features calculated above 
from sklearn.decomposition import PCA
pca = PCA(3)
pca.fit(X)


PCA(n_components=3)

In [60]:
print(pca.components_)
#Feature vector corresponding to the 

print(pca.explained_variance_)

## In pca.components_, we see the feature vector in rows and explained variance will give the eigen values.
'''Hence we can say that the feature vector and eigen values match with the maths'''

[[ 0.1375708   0.25045969 -0.95830278]
 [ 0.69903712  0.66088917  0.27307986]
 [ 0.70172743 -0.70745703 -0.08416157]]
[8.27394258 3.67612927 0.74992815]


'Hence we can say that the feature vector and eigen values match with the maths'

In [61]:
## transformed data is presented in sklearn as
data_transform = pca.transform(X)
print(data_transform)
a = pca.explained_variance_ratio_
print(a)
## ratio define the significance of the each row component.


[[ 2.15142276 -0.17311941 -0.10681648]
 [-3.80418259 -2.88749898 -0.5104355 ]
 [-0.15321328 -0.98688598 -0.26941001]
 [ 4.7065185   1.30153634 -0.65167999]
 [-1.29375788  2.27912632 -0.44919235]
 [-4.0993133   0.1435814   0.80312818]
 [ 1.62582148 -2.23208282 -0.80281431]
 [-2.11448986  3.2512433   0.16837351]
 [ 0.2348172   0.37304031 -0.27513962]
 [ 2.74637697 -1.06894049  2.09398657]]
[0.65149154 0.289459   0.05904946]


In [62]:
h = pca.inverse_transform(data_transform)
print(h)
'''Also we see in sklearn if we re-transform the matrix it will lead to the present data'''

[[7. 4. 3.]
 [4. 1. 8.]
 [6. 3. 5.]
 [8. 6. 1.]
 [8. 5. 7.]
 [7. 2. 9.]
 [5. 3. 3.]
 [9. 5. 8.]
 [7. 4. 5.]
 [8. 2. 2.]]


'Also we see in sklearn if we re-transform the matrix it will lead to the present data'

In [66]:
x = [1,2,3]
y = [4,5,6]
z = np.matmul(x,y)
'''Matrix multiplication and dot product is the same operation.'''

'Matrix multiplication and dot product is the same operation.'