# Tutorial 1 solution


## Q 1. Define a 3 × 3 matrix and determine transpose of A as AT =⇒ (AT)i,j = Ai,j

In [2]:
import numpy as np
x = [[1,4,5],
    [5,6,6],
    [7,8,9]]
A = np.array(x)
print(A)

[[1 4 5]
 [5 6 6]
 [7 8 9]]


In [3]:
AT = np.transpose(A)
print(AT)

[[1 5 7]
 [4 6 8]
 [5 6 9]]


In [4]:
## boolean value as follows:
A == AT

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

## Q 2. Find a practical example to demonstrate applicability of A = AT.

In [5]:
B = np.arange(16).reshape(4,4)
print(B.T)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [6]:
B==B.T
#boolean type statement

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

## Q.3: Print any three elements of the matrix and sum and print

In [7]:
q3 = np.array([[2,4,5],
               [6,7,9],
               [9,21,0]])
print(q3[0],q3[2],q3[1])


[2 4 5] [ 9 21  0] [6 7 9]


In [8]:
sum = 0
for i in range(3):
    sum += q3[i,0]
print(sum)

17


## Q4: Define another matrix of same type and add the two matrices.

In [9]:
q4 = np.arange(9).reshape(3,3)
q4  = q4+q3
# we can specify column and rows in case of size difference in matrix as q4[0:2,3]
print(q4)

[[ 2  5  7]
 [ 9 11 14]
 [15 28  8]]


## Q 5. Multiply the first matrix with a scalar and then add this new matrix to the second matrix

In [10]:
q5 = q3*1.5 + q4
print(q5)
# multiplying the scaler will lead to multiplying all the elemnets of matrix with the scaler quantity.


[[ 5.  11.  14.5]
 [18.  21.5 27.5]
 [28.5 59.5  8. ]]


## Q 6. Add a vector b to the original matrix A using C = A + b i.e. Ci,j = Ai,j + bj . This is essentially anoperation that adds vector b to each row of the matrix A.

In [11]:
b = np.array([1,2,4])
for i in range(len(A)):
    C = A[i,:]+b
    print(C)
# as we add the matrix A with b vector we see that each column is increase with th first value of b or b is added to each row to the matrix A

[2 6 9]
[ 6  8 10]
[ 8 10 13]


In [12]:
# also version of C 
C = A + b 
print(C)
# b if same type as that of will add to each row

[[ 2  6  9]
 [ 6  8 10]
 [ 8 10 13]]


## Q7: Analyse right and left invert matrices for a square and a non-square matrix

In [13]:
# as the equation Ax = b we consider the matrix A and invert the matrix
#*Square Matrix*
q7 = np.linalg.inv(A)
print(q7)
#please note that inverse exists for the square matrix
new_q7 = np.linalg.inv(q7)
print(new_q7)

[[-0.375  -0.25    0.375 ]
 [ 0.1875  1.625  -1.1875]
 [ 0.125  -1.25    0.875 ]]
[[1. 4. 5.]
 [5. 6. 6.]
 [7. 8. 9.]]


In [14]:
# now Applying inverse to non square matrix ax = b
a = np.array([[1,23,4],
            [9,33,4]])
inverse = np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

## Q 8. Show that L0 can not be a norm.
## Q 9. Choose a non-singular and non-Identity matrix and determine its eigenvalues and eigenvectors

In [32]:
## Singular matrix means determinent zero and non identity is determinet ==1
q9 = np.array([[1,4,5],
              [5,9,3],
              [8,22,33]])
det = np.linalg.det(q9)
evalue, evector = np.linalg.eig(q9)
print("Deteminent of q9: ",det)
## this shows that it is a non singular and non identity matrix
print(evalue)
# this is the list of eigen value 
print(evector)
#this is the array of eigen vector where each column is a eigen vector and here 3 eigen vector

Deteminent of q9:  -142.99999999999994
[37.16532244 -0.5981325   6.43281006]
[[-0.14997459 -0.86647339  0.01563503]
 [-0.13100469  0.48644887 -0.7724176 ]
 [-0.97997214 -0.11221123  0.63492251]]


In [27]:
#proof of eigen vector and values.
#matrix*eigen vector = eigen value*vector
p = evalue[0]*evector[:,0]
print(p)
z = np.matmul(q9,evector[:,0])
print(z)


[ -5.57385405  -4.8688316  -36.42098052]
[ -5.57385405  -4.8688316  -36.42098052]


## Q 10: In the above example, show that the determinant of the matrix is given by product of its eigenvalues

In [62]:
Z = evalue[0]*evalue[1]*evalue[2]
print("Value of product of eigen values: ",Z)
print("Deteminent of q9: ",det)
## clearly determinent of q9 == eigen values

Value of product of eigen values:  -142.9999999999998
Deteminent of q9:  -142.99999999999994


## Q11: Choose any three matrices of same size and show that T r(ABC) = T r(CAB) = T r(BCA).

In [35]:
Mat1 = np.arange(4).reshape(2,2)
Mat2 = np.arange(8,12).reshape(2,2)
Mat3 = np.arange(20,24).reshape(2,2)

In [40]:
Mat1*Mat2
# elemental multiplication
m1 = np.matmul(Mat1,np.matmul(Mat2,Mat3))
print(m1)
#matrix muliplication
print(np.trace(m1))

[[ 442  463]
 [2042 2139]]
2581


In [41]:
m2 = np.matmul(Mat3,np.matmul(Mat1,Mat2))
print(m2)
print(np.trace(m2))

[[1166 1291]
 [1278 1415]]
2581


In [42]:
m3 = np.matmul(Mat2,np.matmul(Mat3,Mat1))
print(m3)
print(np.trace(m3))
''' As we can see clearly that Trace of 1 == Trace of 2 == Trace of 3 i.e. 2581'''

[[ 750 1483]
 [ 926 1831]]
2581


## Q 12. Do the above exercise by having matrices of different sizes but making sure that their product is possible.


In [53]:
'''Now for the non square matrix we apply the above products'''
import numpy as np
matrix_1 = np.arange(18,24).reshape(3,2)
matrix_2 = np.arange(10,16).reshape(2,3)
matrix_3 = np.arange(2,11).reshape(3,3)

In [57]:
M1 = np.matmul(matrix_3,np.matmul(matrix_1,matrix_2))
print(M1)
print(np.trace(M1))

[[ 4349  4726  5103]
 [ 8606  9352 10098]
 [12863 13978 15093]]
28794


In [58]:
M2 = np.matmul(matrix_1,np.matmul(matrix_2,matrix_3))
print(M2)
print(np.trace(M2))

[[ 7182  8574  9966]
 [ 7956  9498 11040]
 [ 8730 10422 12114]]
28794


In [60]:
M3 = np.matmul(matrix_2,np.matmul(matrix_3,matrix_1))
print(M3)
print(np.trace(M3))
'''Now for the different matrix of size 3,2 and 2,3 also satisfy the above product rule'''

[[12372 12984]
 [15648 16422]]
28794


## Q 13. Show how a circle is distorted by the eignvalues and eigenvectors of a matrix.

In [107]:
'''suppose that the 100, 100 values for the circle eigen values so when we change the values to 210,180.'''
import math 
from PIL import Image, ImageDraw 
  
w, h = 220, 190
shape = [(40, 40), (w - 10, h - 10)] 
shape1 = [(40,40), (100 , 100)]
# creating new Image object 
img = Image.new("RGB", (w, h)) 
  
# create ellipse image 

img1 = ImageDraw.Draw(img)   
img1.ellipse(shape1 ,outline="red")

img1 = ImageDraw.Draw(img)   
img1.ellipse(shape, outline ="green") 
img.show() 

# Q 14. A matrix is singular if and only if any of the eigenvalues are zero.


In [87]:
'''A matrix is singular if and only if determinent is zero but the eigenvalues is non zero than also it can be a singular matrix'''
singular = np.array([[3,8,1],
                    [-4,1,1],
                    [-4,1,1]])
determ = np.linalg.det(singular)
print(determ)
value,vector = np.linalg.eig(singular)
print(value)
print(vector)

##proof is shown here

0.0
[2.50000000e+00+5.97913037j 2.50000000e+00-5.97913037j
 6.82496752e-17+0.j        ]
[[ 0.72760688+0.j          0.72760688-0.j          0.19245009+0.j        ]
 [-0.0404226 +0.48338404j -0.0404226 -0.48338404j -0.19245009+0.j        ]
 [-0.0404226 +0.48338404j -0.0404226 -0.48338404j  0.96225045+0.j        ]]


In [82]:
'''Inverse is not possible for the matrix and eigen value is zero therefor '''
D =  np.array([[3,0,0],
              [-6,-3,0],
              [3,3,0]])
val, vect = np.linalg.eig(D)
print(val)
print(vect)
print(np.linalg.det(D))
'''So it is proven that only '''

[ 0. -3.  3.]
[[ 0.          0.          0.70710678]
 [ 0.          0.70710678 -0.70710678]
 [ 1.         -0.70710678  0.        ]]
0.0
