# Matrix decomposition and construction
<b> 2D Example of $A = Q \Lambda Q^{-1}$ 
#This is true for a non-symmetric matrix.

In [2]:
import numpy as np

In [4]:
listv1 = [1, 1] # these are my eigenvector arrays
listv2 = [2, 3]
listlambda = [-2, 7] # this is my eigenvalues array
lambdamatrix=np.zeros((2,2))
v1 = np.array(listv1)
v2 = np.array(listv2)
lambdaarray = np.array(listlambda)
print(v1)
print(v2)
print(lambdaarray)
print(type(v1))
print(type(lambdaarray))


[1 1]
[2 3]
[-2  7]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
Q =np.column_stack((v1,v2)) # make Q matrix by stacking eigenvectors as columns
print(Q)

[[1 2]
 [1 3]]


<b> Let check if the Q is Orthogonal or not i.e. is $Q^T = Q^{-1}$ ?

In [7]:
C = np.linalg.inv(Q)
C

array([[ 3., -2.],
       [-1.,  1.]])

In [8]:
D = np.transpose(Q)
D

array([[1, 1],
       [2, 3]])

In [9]:
lambdamatrix = np.array([[lambdaarray[0],0],[0,lambdaarray[1]]]) # Let us the diagonal matrix of eigenvalues
print(lambdamatrix)

[[-2  0]
 [ 0  7]]


In [10]:
import numpy as np
A = np.matmul(Q,np.matmul(lambdamatrix,np.linalg.inv(Q))) # construct the matrix
A

array([[-20.,  18.],
       [-27.,  25.]])

# Let us repeat the exercise for a 3 x 3 matrix

In [15]:
listv1 = [1, 2, 4] # these are my eigenvector arrays
listv2 = [5, 7, 8]
listv3 = [5, 9, 1]
listlambda = [-2, 3, 2] # this is my eigenvalues array
lambdamatrix=np.zeros((3,3))
v1 = np.array(listv1)
v2 = np.array(listv2)
v3 = np.array(listv3)
lambdaarray = np.array(listlambda)
print(v1)
print(v2)
print(v3)
print(lambdaarray)
print(type(v1))
print(type(lambdaarray))
print(type(Q))

[1 2 4]
[5 7 8]
[5 9 1]
[-2  3  2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
#Q =np.column_stack((v1/np.linalg.norm(v1),v2/np.linalg.norm(v2),v3/np.linalg.norm(v3)))
Q =np.column_stack((v1,v2,v3))
print(Q)

[[1 5 5]
 [2 7 9]
 [4 8 1]]


In [21]:
lambdamatrix = np.array([[lambdaarray[0],0,0],[0,lambdaarray[1],0],[0,0,lambdaarray[2]]])
print(lambdamatrix)

[[-2  0  0]
 [ 0  3  0]
 [ 0  0  2]]


In [22]:
import numpy as np
A = np.matmul(Q,np.matmul(lambdamatrix,np.linalg.inv(Q)))

In [23]:
A

array([[ 11.55555556,  -5.22222222,  -0.77777778],
       [ 16.84444444,  -7.17777778,  -1.62222222],
       [ 29.15555556, -15.82222222,  -1.37777778]])

In [24]:
w,v = np.linalg.eig(A)
print(w)
print(v)

[-2.  3.  2.]
[[ 0.21821789  0.42562827 -0.48336824]
 [ 0.43643578  0.59587957 -0.87006284]
 [ 0.87287156  0.68100522 -0.09667365]]


In [25]:
unitv1 = v1 / np.linalg.norm(v1)
unitv2 = v2 / np.linalg.norm(v2)
unitv3 = v3 / np.linalg.norm(v3)
print(unitv1)
print(unitv2)
print(unitv3)

[0.21821789 0.43643578 0.87287156]
[0.42562827 0.59587957 0.68100522]
[0.48336824 0.87006284 0.09667365]


In [26]:
print(v)

[[ 0.21821789  0.42562827 -0.48336824]
 [ 0.43643578  0.59587957 -0.87006284]
 [ 0.87287156  0.68100522 -0.09667365]]


In [27]:
invV = np.linalg.inv(v)
print(invV)

[[-6.619276    3.56422554  1.01835015]
 [ 8.87576809 -4.95998805  0.261052  ]
 [ 2.75842145 -2.75842145  0.68960536]]


In [28]:
transposeV = np.transpose(v)
print(transposeV)

[[ 0.21821789  0.43643578  0.87287156]
 [ 0.42562827  0.59587957  0.68100522]
 [-0.48336824 -0.87006284 -0.09667365]]


Note that transpose of Q is not equal to the inverse of Q. What does it mean ?

<b> Let us check what are the eigenvalues and eigenvectors of a real symmetric matrix.

In [29]:
A =np.array([[1,2,3], # define a new matrix
            [2,4,5],
            [3,5,7]])
A

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 7]])

In [30]:
type(A)

numpy.ndarray

In [31]:
w,v = np.linalg.eig(A)
print(w)
print(v)

[11.90897874 -0.24781764  0.3388389 ]
[[ 0.31351175  0.90082516  0.30037379]
 [ 0.56280048  0.07850569 -0.82285629]
 [ 0.7648307  -0.42702563  0.48237237]]


In [32]:
invV = np.linalg.inv(v)
print(invV)

[[ 0.31351175  0.56280048  0.7648307 ]
 [ 0.90082516  0.07850569 -0.42702563]
 [ 0.30037379 -0.82285629  0.48237237]]


In [33]:
transposeV = np.transpose(v)
print(transposeV)

[[ 0.31351175  0.56280048  0.7648307 ]
 [ 0.90082516  0.07850569 -0.42702563]
 [ 0.30037379 -0.82285629  0.48237237]]


For a symmetric matrix, $Q^T = Q^{-1}$ where Q is a matrix containing eigenvectors of a symmetric matrix as columns 