# Mean, Variance and Covariance with numpy
We have done some of these in tutorial 2 using first principals. Now we will use numpy directly and will consolidate our fundamentals. Pay attendtion to theory and compare the inference of these numerical examples

In [1]:
import numpy as np
from numpy import array # note that this time we are exporting array and mean directly so we dont have to use np.array etc.
from numpy import mean
from numpy import var

Calculating "mean" using mumpy

In [17]:
v = array([1,2,3,4,5,6])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


Calculating "mean" of each row or column using mumpy

In [18]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_mean = mean(M, axis=0)
print(col_mean)
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


Variance calculation using numpy

In [19]:
v = array([1,2,3,4,5,6])
print(v)
result = var(v, ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


Variance calculation of rows and columns using numpy

In [22]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_variance = var(M, ddof=1, axis=0)
print(col_variance)
row_variance = var(M, ddof=1, axis=1)
print(row_variance)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


Standard deviation from variance

In [24]:
s = np.sqrt(row_variance)
print(s)

[1.87082869 1.87082869]


Standard deviation of rows and columns using numpy

In [26]:
M = array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(M)
col_std = np.std(M, ddof=1, axis=0)
print(col_std)
row_std = np.std(M, ddof=1, axis=1)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


Covariance between two arrays using numpy

In [2]:
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([9,8,7,6,5,4,3,2,1])
print(y)
x_var = np.var(x)
print(x_var)
y_var = np.var(y)
print(y_var)
covariance = np.cov(x,y)
print(covariance)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
6.666666666666667
6.666666666666667
[[ 7.5 -7.5]
 [-7.5  7.5]]
