# Singular Value Decomposition of a Matrix
$ A = U D V^T$

In [2]:
import numpy as np

In [70]:
A = np.array([[2,5],
              [1,4],
              [0,0],
              [0,0]])

In [71]:
type(A)

numpy.ndarray

In [72]:
U = np.matmul(A,np.transpose(A))
U

array([[29, 22,  0,  0],
       [22, 17,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [73]:
Uw,Uv=np.linalg.eig(U)
print(Uw)
print(Uv)

[45.8035085  0.1964915  0.         0.       ]
[[ 0.79470668 -0.60699365  0.          0.        ]
 [ 0.60699365  0.79470668  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [74]:
V = np.matmul(np.transpose(A),A)
V

array([[ 5, 14],
       [14, 41]])

In [75]:
Vw,Vv=np.linalg.eig(V)
print(Vw)
print(Vv)

[ 0.1964915 45.8035085]
[[-0.9458732  -0.32453643]
 [ 0.32453643 -0.9458732 ]]


In [76]:
Diag = np.sqrt(Vw)
Diag

array([0.44327362, 6.76782894])

In [77]:
D = np.array([[Diag[0],0],
              [0,Diag[1]],
              [0,0],
              [0,0]])
D

array([[0.44327362, 0.        ],
       [0.        , 6.76782894],
       [0.        , 0.        ],
       [0.        , 0.        ]])

<b> Let us check if get the original matrix or not

In [78]:
B = np.matmul(Uv,np.matmul(D,np.transpose(Vv)))
B

array([[ 1.,  4.],
       [-2., -5.],
       [ 0.,  0.],
       [ 0.,  0.]])

<b> Let us apply the direct SVD function from numpy library

In [79]:
U,D,V=np.linalg.svd(A)
print(U)

[[-0.79470668 -0.60699365  0.          0.        ]
 [-0.60699365  0.79470668  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [80]:
print(D)

[6.76782894 0.44327362]


In [81]:
print(V)

[[-0.32453643 -0.9458732 ]
 [-0.9458732   0.32453643]]


<b> Let us try a 3 x 3 matrix

In [3]:
A = np.array([[3,4,6],
              [7,1,9],
              [5,6,2]])

In [5]:
U = np.matmul(A,np.transpose(A))
Uw,Uv=np.linalg.eig(U)
V = np.matmul(np.transpose(A),A)
Vw,Vv=np.linalg.eig(V)
Diag = np.sqrt(Vw)
D = np.array([[Diag[0],0,0],
              [0,Diag[1],0],
              [0,0,Diag[2]]])
B = np.matmul(Uv,np.matmul(D,np.transpose(Vv)))
B

array([[ 6.03622283,  1.51204039,  4.71993092],
       [ 6.15859722,  7.02666344,  6.61042217],
       [ 2.93865519, -1.15746912,  7.41785487]])